site_name: Pixano Documentation
theme:
  name: material
  logo: assets/pixano_white.png
  favicon: assets/pixano.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: pink
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: pink
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Poppins
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.integrate
repo_url: https://github.com/pixano/pixano
repo_name: pixano/pixano
copyright: Licensed under the CeCILL-C license
extra:
  social:
    - icon: material/email-outline
      link: mailto:pixano@cea.fr
      name: Contact us
    - icon: material/web
      link: https://list.cea.fr/en/
      name: CEA LIST
    - icon: fontawesome/brands/github 
      link: https://github.com/pixano/pixano
      name: Pixano on GitHub
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: ["pixano"]
        import:
          - https://docs.python.org/3.10/objects.inv
          - https://numpy.org/doc/1.23/objects.inv
          - https://pandas.pydata.org/pandas-docs/version/1.5/objects.inv
          - https://pillow.readthedocs.io/en/stable/objects.inv
          - https://arrow.apache.org/docs/objects.inv
          - https://docs.pydantic.dev/2.0/objects.inv # no objects.inv available for 1.10
          - https://ipython.readthedocs.io/en/8.13.2/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          show_submodules: no
          docstring_section_style: table
          members_order: alphabetical
          merge_init_into_class: yes
          show_root_heading: true
          show_source: true
          heading_level: 1

          
nav:

- "Home": index.md

- "Getting started":
  - user/index.md
  - "Installing Pixano": user/install.md
  - "Importing datasets": user/import.md
  - "Exporting datasets": user/export.md
  - "Launching an app": user/launch.md
  - "Using Pixano Explorer": user/explorer.md
  - "Using Pixano Annotator": user/annotator.md
  
- "API reference": 
  - code/index.md

  - "analytics":
    - "feature_statistics": code/analytics/feature_statistics.md

  - "apps":
    - "core":
      - "db_utils": code/apps/core/db_utils.md
      - "main": code/apps/core/main.md
      - "serve": code/apps/core/serve.md
    - "annotator": code/apps/annotator.md
    - "explorer": code/apps/explorer.md

  - "data":
    - "importers":
      - "DataImporter": code/data/importers/data_importer.md
      - "CocoImporter": code/data/importers/coco_importer.md
      - "ImageImporter": code/data/importers/image_importer.md
      - "DOTAImporter": code/data/importers/dota_importer.md
      - "LegacyImporter": code/data/importers/legacy_importer.md
    - "exporters":
      - "DataExporter": code/data/exporters/data_exporter.md
      - "CocoExporter": code/data/exporters/coco_exporter.md
    - "dataset": code/data/dataset.md

  - "models":
    - "InferenceModel": code/models/inference_model.md

  - "transforms":
    - "boxes": code/transforms/boxes.md
    - "image": code/transforms/image.md
    - "labels": code/transforms/labels.md
  
  - "types": code/types.md

- "Pixano Inference": https://pixano.github.io/pixano-inference/
