site_name: Pixano Documentation
theme:
  name: material
  logo: assets/pixano_white.png
  favicon: assets/pixano.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: pink
  font:
    text: Poppins
  features:
    - navigation.instant
    - navigation.sections
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: ["../pixano"]
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          show_submodules: no
          docstring_section_style: list
          members_order: alphabetical
          merge_init_into_class: no
          show_root_heading: true
          show_source: true
          heading_level: 1
repo_url: https://github.com/pixano/pixano
repo_name: pixano/pixano

nav:
- "Getting started": index.md

- "User guides":

  - "Pixano Explorer": user/explorer.md
  - "Pixano Annotator": user/annotator.md
  
- "API reference":

  - "analytics":
    - "feature_statistics": code/analytics/feature_statistics.md

  - "apps":
    - "core":
      - "db_utils": code/apps/core/db_utils.md
      - "main": code/apps/core/main.md
      - "serve": code/apps/core/serve.md
    - "annotator": code/apps/annotator.md
    - "explorer": code/apps/explorer.md

  - "core":
    - "arrow_types": code/core/arrow_types.md
    - "dataset": code/core/dataset.md

  - "data":
    - "DataLoader": code/data/data_loader.md
    - "CocoLoader": code/data/coco_loader.md
    - "ImageLoader": code/data/image_loader.md
    - "models": code/data/models.md

  - "inference":
    - "InferenceModel": code/inference/inference_model.md

  - "notebook":
    - "display": code/notebook/display.md

  - "tools":
    - "converter": code/tools/converter.md

  - "transforms":
    - "boxes": code/transforms/boxes.md
    - "image": code/transforms/image.md
    - "labels": code/transforms/labels.md
