site_name: Pixano Documentation
theme:
  name: material
  logo: assets/pixano_white.png
  favicon: assets/pixano.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: pink
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: pink
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Poppins
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
repo_url: https://github.com/pixano/pixano
repo_name: pixano/pixano
copyright: Licensed under the CeCILL-C license
extra:
  social:
    - icon: material/email-outline
      link: mailto:pixano@cea.fr
      name: Contact us
    - icon: material/web
      link: https://list.cea.fr/en/
      name: CEA LIST
    - icon: fontawesome/brands/github 
      link: https://github.com/pixano/pixano
      name: Pixano on GitHub
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: ["../pixano"]
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          show_submodules: no
          docstring_section_style: list
          members_order: alphabetical
          merge_init_into_class: no
          show_root_heading: true
          show_source: true
          heading_level: 1

          
nav:

- "User guides":

  - "Pixano Explorer": user/explorer.md
  - "Pixano Annotator": user/annotator.md
  
- "API reference":

  - "analytics":
    - "feature_statistics": code/analytics/feature_statistics.md

  - "apps":
    - "core":
      - "db_utils": code/apps/core/db_utils.md
      - "main": code/apps/core/main.md
      - "serve": code/apps/core/serve.md
    - "annotator": code/apps/annotator.md
    - "explorer": code/apps/explorer.md

  - "core":
    - "arrow_types": code/core/arrow_types.md
    - "dataset": code/core/dataset.md

  - "data":
    - "DataLoader": code/data/data_loader.md
    - "CocoLoader": code/data/coco_loader.md
    - "ImageLoader": code/data/image_loader.md
    - "models": code/data/models.md

  - "inference":
    - "InferenceModel": code/inference/inference_model.md

  - "notebook":
    - "display": code/notebook/display.md

  - "tools":
    - "converter": code/tools/converter.md

  - "transforms":
    - "boxes": code/transforms/boxes.md
    - "image": code/transforms/image.md
    - "labels": code/transforms/labels.md
