# @Copyright: CEA-LIST/DIASI/SIALV/LVA (2023)
# @Author: CEA-LIST/DIASI/SIALV/LVA <pixano@cea.fr>
# @License: CECILL-C
#
# This software is a collaborative computer program whose purpose is to
# generate and explore labeled data for computer vision applications.
# This software is governed by the CeCILL-C license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/ or redistribute the software under the terms of the CeCILL-C
# license as circulated by CEA, CNRS and INRIA at the following URL
#
# http://www.cecill.info

# This workflow will lint UI and markdown code with Prettier
# For more information see: https://github.com/marketplace/actions/prettier-action

name: Lint UI and markdown code

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_plugins: "prettier-plugin-svelte"
          prettier_options: --check **/*.{js,ts,svelte,json,md}
